// src/lib/components/drawer/DrawerTheme.svelte
<script lang="ts">
  // Theme selection panel. Each card is rendered with its own theme colors.
  import { onMount } from 'svelte';
  import type { Theme } from '$lib/types';
  import { settings } from '$lib/stores/settings';
  import { activeTheme, applyTheme } from '$lib/stores/theme';
  import { getThemes, applyThemeByName, onThemesChanged } from '$lib/ipc';
  import type { UnlistenFn } from '@tauri-apps/api/event';

  let themes = $state<Theme[]>([]);
  let activeName = $derived($settings.theme);

  onMount(() => {
    const cleanups: UnlistenFn[] = [];

    (async () => {
      themes = await getThemes();

      cleanups.push(
        await onThemesChanged((updated) => {
          themes = updated;
        }),
      );
    })();

    return () => { for (const fn of cleanups) fn(); };
  });

  async function select(theme: Theme) {
    // Apply immediately for instant preview.
    applyTheme(theme);
    // Persist via backend (also updates settings store via settings:changed).
    const applied = await applyThemeByName(theme.name);
    applyTheme(applied);
    settings.update((s) => ({ ...s, theme: theme.name }));
  }
</script>

<div class="panel">
  <p class="heading">Themes</p>

  {#each themes as theme (theme.name)}
    {@const bg = theme.colors['--color-background'] ?? '#2f384b'}
    {@const fg = theme.colors['--color-foreground'] ?? '#d7e1f4'}
    {@const accent = theme.colors['--color-accent'] ?? '#e25d60'}
    {@const isActive = theme.name === activeName}
    <button
      class="card"
      class:active={isActive}
      style="background:{bg}; border-color:{accent};"
      onclick={() => select(theme)}
    >
      <span class="card-name" style="color:{fg}">{theme.name}</span>
      {#if theme.is_custom}
        <span class="badge" style="color:{accent}">custom</span>
      {/if}
      {#if isActive}
        <svg width="18" height="18" viewBox="0 0 24 24" style="fill:{accent}; flex-shrink:0;">
          <path d="M9 16.2L4.8 12l-1.4 1.4L9 19 21 7l-1.4-1.4L9 16.2z"/>
        </svg>
      {/if}
    </button>
  {/each}
</div>

<style>
  .panel {
    padding: 8px 12px;
    overflow-y: auto;
    height: 100%;
  }

  .heading {
    font-size: 0.7rem;
    font-weight: 700;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    color: var(--color-foreground-darker, var(--color-foreground));
    margin-bottom: 8px;
    padding-bottom: 6px;
    border-bottom: 1px solid var(--color-separator);
  }

  .card {
    align-items: center;
    border-left: 3px solid;
    border-top: none;
    border-right: none;
    border-bottom: none;
    border-radius: 0 4px 4px 0;
    cursor: pointer;
    display: flex;
    gap: 8px;
    justify-content: space-between;
    margin: 6px 0;
    min-height: 44px;
    padding: 0 12px;
    width: 100%;
    transition: opacity 0.15s;
  }

  .card:hover {
    opacity: 0.9;
  }

  .card-name {
    font-size: 0.8rem;
    letter-spacing: 0.04em;
    text-align: left;
    flex: 1;
  }

  .badge {
    font-size: 0.6rem;
    letter-spacing: 0.06em;
    text-transform: uppercase;
    opacity: 0.7;
  }
</style>

// src/renderer/components/drawer/Drawer-theme.vue
<template>
  <div class="Container">
    <p class="Drawer-heading">Themes</p>
    <div
      v-for="(t, i) in themer.themes"
      :key="i"
      class="Setting-wrapper"
      :style="
        `background-color: ${themer.getThemeValue(
          t,
          '--color-background'
        )}; border-color: ${themer.getThemeValue(
          t,
          '--color-accent'
        )}`
      "
      @click="selectTheme(themer.getThemeName(t))"
    >
      <p
        class="Setting-title"
        :style="
          `color: ${themer.getThemeValue(t, '--color-foreground')}`
        "
      >
        {{ themer.getThemeName(t) }}
      </p>
      <transition name="fade">
        <svg
          v-if="theme === themer.getThemeName(t)"
          xmlns="http://www.w3.org/2000/svg"
          width="6.6vw"
          height="6.6vw"
          viewBox="0 0 24 24"
        >
          <path d="M0 0h24v24H0z" fill="none" />
          <path
            d="M9 16.2L4.8 12l-1.4 1.4L9 19 21 7l-1.4-1.4L9 16.2z"
            fill="var(--color-accent)"
          />
        </svg>
      </transition>
    </div>
  </div>
</template>

<script>
import themer from '@/utils/Themer'
export default {
  name: 'Drawer-theme',

  data() {
    return {
      themer
    }
  },

  computed: {
    theme() {
      return this.$store.getters.theme
    }
  },

  methods: {
    selectTheme(themeName) {
      const payload = { key: 'theme', val: themeName }
      this.$store.dispatch('setSetting', payload)
      this.$store.dispatch('setViewState', payload)
      this.themer.apply(themeName)
    }
  }
}
</script>

<style lang="scss" scoped>
.Container {
  max-height: calc(100% - 10vw);
  overflow-y: auto;
}

.Setting-wrapper {
  align-items: center;
  border-left: 0.83vw solid;
  border-radius: 0 1.1vw 1.1vw 0;
  display: flex;
  justify-content: space-between;
  margin: 3.3vw 0;
  min-height: 13.3vw;
  padding: 0 3.3vw;
}

.Setting-title {
  font-size: 0.7rem;
  letter-spacing: 0.05rem;
}
</style>
