// src/lib/components/drawer/DrawerSettings.svelte
<script lang="ts">
  // App settings: boolean toggles and global shortcuts.
  import { settings } from '$lib/stores/settings';
  import { setSetting, reloadShortcuts } from '$lib/ipc';
  import ShortcutInput from '$lib/components/ShortcutInput.svelte';

  async function toggle(dbKey: string, current: boolean) {
    const updated = await setSetting(dbKey, current ? 'false' : 'true');
    settings.set(updated);
  }

  async function setShortcut(dbKey: string, value: string) {
    const updated = await setSetting(dbKey, value);
    settings.set(updated);
    await reloadShortcuts();
  }
</script>

<div class="panel">
  <p class="heading">Settings</p>

  <button class="row" onclick={() => toggle('always_on_top', $settings.always_on_top)}>
    <span class="label">Always On Top</span>
    <span class="checkbox" class:checked={$settings.always_on_top}></span>
  </button>

  {#if $settings.always_on_top}
    <button class="row" onclick={() => toggle('break_always_on_top', $settings.break_always_on_top)}>
      <span class="label">Disable On Top During Breaks</span>
      <span class="checkbox" class:checked={$settings.break_always_on_top}></span>
    </button>
  {/if}

  <button class="row" onclick={() => toggle('auto_start_work', $settings.auto_start_work)}>
    <span class="label">Auto-start Work Timer</span>
    <span class="checkbox" class:checked={$settings.auto_start_work}></span>
  </button>

  <button class="row" onclick={() => toggle('auto_start_break', $settings.auto_start_break)}>
    <span class="label">Auto-start Break Timer</span>
    <span class="checkbox" class:checked={$settings.auto_start_break}></span>
  </button>

  <button class="row" onclick={() => toggle('tick_sounds_work', $settings.tick_sounds_during_work)}>
    <span class="label">Tick Sounds — Work</span>
    <span class="checkbox" class:checked={$settings.tick_sounds_during_work}></span>
  </button>

  <button class="row" onclick={() => toggle('tick_sounds_break', $settings.tick_sounds_during_break)}>
    <span class="label">Tick Sounds — Break</span>
    <span class="checkbox" class:checked={$settings.tick_sounds_during_break}></span>
  </button>

  <button class="row" onclick={() => toggle('notifications', $settings.notifications_enabled)}>
    <span class="label">Desktop Notifications</span>
    <span class="checkbox" class:checked={$settings.notifications_enabled}></span>
  </button>

  <button class="row" onclick={() => toggle('min_to_tray', $settings.min_to_tray)}>
    <span class="label">Minimize to Tray</span>
    <span class="checkbox" class:checked={$settings.min_to_tray}></span>
  </button>

  <button class="row" onclick={() => toggle('min_to_tray_on_close', $settings.min_to_tray_on_close)}>
    <span class="label">Minimize to Tray on Close</span>
    <span class="checkbox" class:checked={$settings.min_to_tray_on_close}></span>
  </button>

  <p class="heading" style="margin-top: 16px;">Global Shortcuts</p>

  <div class="row row--shortcut">
    <span class="label">Toggle Timer</span>
    <ShortcutInput
      value={$settings.shortcut_toggle}
      onchange={(v) => setShortcut('shortcut_toggle', v)}
    />
  </div>

  <div class="row row--shortcut">
    <span class="label">Reset Timer</span>
    <ShortcutInput
      value={$settings.shortcut_reset}
      onchange={(v) => setShortcut('shortcut_reset', v)}
    />
  </div>

  <div class="row row--shortcut">
    <span class="label">Skip Round</span>
    <ShortcutInput
      value={$settings.shortcut_skip}
      onchange={(v) => setShortcut('shortcut_skip', v)}
    />
  </div>
</div>

<style>
  .panel {
    padding: 8px 12px;
    overflow-y: auto;
    height: 100%;
  }

  .heading {
    font-size: 0.7rem;
    font-weight: 700;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    color: var(--color-foreground-darker, var(--color-foreground));
    margin-bottom: 8px;
    padding-bottom: 6px;
    border-bottom: 1px solid var(--color-separator);
  }

  .row {
    background: var(--color-background);
    border: none;
    border-radius: 4px;
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin: 6px 0;
    padding: 10px 12px;
    cursor: pointer;
    width: 100%;
    text-align: left;
    transition: background 0.15s;
  }

  .row:hover {
    background: color-mix(in oklch, var(--color-background) 88%, var(--color-foreground) 12%);
  }

  .row--shortcut {
    cursor: default;
  }

  .row--shortcut:hover {
    background: var(--color-background);
  }

  .label {
    color: var(--color-foreground-darker, var(--color-foreground));
    font-size: 0.8rem;
    letter-spacing: 0.04em;
  }

  .checkbox {
    display: inline-block;
    width: 16px;
    height: 16px;
    border-radius: 50%;
    border: 2px solid color-mix(in oklch, var(--color-foreground) 25%, transparent);
    background: var(--color-background);
    flex-shrink: 0;
    transition: background 0.15s, border-color 0.15s;
  }

  .checkbox.checked {
    background: var(--color-accent);
    border-color: var(--color-background);
  }

  .row:hover .checkbox:not(.checked) {
    border-color: var(--color-accent);
  }
</style>

// src/renderer/components/drawer/Drawer-settings.vue
<template>
  <div class="Container">
    <p class="Drawer-heading">Settings</p>
    <div class="Setting-wrapper">
      <p class="Setting-title">Always On Top</p>
      <div
        class="Checkbox"
        @click="selectAlwaysOnTop"
        :class="alwaysOnTop ? 'is-active' : 'is-inactive'"
      ></div>
    </div>
    <transition name="slide-left" mode="in-out">
      <div class="Setting-wrapper" v-show="alwaysOnTop">
        <p class="Setting-title">Deactivate Always On Top on Breaks</p>
        <div
          class="Checkbox"
          @click="selectBreakAlwaysOnTop"
          :class="breakAlwaysOnTop ? 'is-active' : 'is-inactive'"
          ref="breakAlwaysOnTopCheckbox"
        ></div>
      </div>
    </transition>
    <div class="Setting-wrapper">
      <p class="Setting-title">Auto-start Work Timer</p>
      <div
        class="Checkbox"
        @click="selectAutoStartWorkTimer"
        :class="autoStartWorkTimer ? 'is-active' : 'is-inactive'"
      ></div>
    </div>
    <div class="Setting-wrapper">
      <p class="Setting-title">Auto-start Break Timer</p>
      <div
        class="Checkbox"
        @click="selectAutoStartBreakTimer"
        :class="autoStartBreakTimer ? 'is-active' : 'is-inactive'"
      ></div>
    </div>
    <div class="Setting-wrapper">
      <p class="Setting-title">Tick Sounds - Work</p>
      <div
        class="Checkbox"
        @click="selectTickSounds"
        :class="tickSounds ? 'is-active' : 'is-inactive'"
      ></div>
    </div>
    <div class="Setting-wrapper">
      <p class="Setting-title">Tick Sounds - Break</p>
      <div
        class="Checkbox"
        @click="selectTickSoundsDuringBreak"
        :class="tickSoundsDuringBreak ? 'is-active' : 'is-inactive'"
      ></div>
    </div>
    <div class="Setting-wrapper">
      <p class="Setting-title">Desktop Notifications</p>
      <div
        class="Checkbox"
        @click="selectNotifications"
        :class="notifications ? 'is-active' : 'is-inactive'"
      ></div>
    </div>
    <div class="Setting-wrapper">
      <p class="Setting-title">Minimize to Tray</p>
      <div
        class="Checkbox"
        @click="selectMinToTray"
        :class="minToTray ? 'is-active' : 'is-inactive'"
      ></div>
    </div>
    <div class="Setting-wrapper">
      <p class="Setting-title">Minimize to Tray on Close</p>
      <div
        class="Checkbox"
        @click="selectMinToTrayOnClose"
        :class="minToTrayOnClose ? 'is-active' : 'is-inactive'"
      ></div>
    </div>
    <div class="Setting-wrapper">
      <p class="Setting-title">Right Click to Reset Round</p>
      <div
        class="Checkbox"
        @click="selectRightClickToResetRound"
        :class="rightClickToResetRound ? 'is-active' : 'is-inactive'"
      ></div>
    </div>

    <p class="Drawer-heading">Global Shortcuts</p>

    <div class="Setting-wrapper">
      <p class="Setting-title">Toggle Timer</p>
      <shortcut-input
        :value="globalShortcuts['call-timer-toggle']"
        @input="shortcut => setGlobalShortcut('call-timer-toggle', shortcut)"
      />
    </div>
    <div class="Setting-wrapper">
      <p class="Setting-title">Reset Timer</p>
      <shortcut-input
        :value="globalShortcuts['call-timer-reset']"
        @input="shortcut => setGlobalShortcut('call-timer-reset', shortcut)"
      />
    </div>
    <div class="Setting-wrapper">
      <p class="Setting-title">Skip Round</p>
      <shortcut-input
        :value="globalShortcuts['call-timer-skip']"
        @input="shortcut => setGlobalShortcut('call-timer-skip', shortcut)"
      />
    </div>
  </div>
</template>

<script>
import { ipcRenderer } from 'electron'
import ShortcutInput from '../ShortcutInput'

export default {
  name: 'Drawer-settings',

  computed: {
    alwaysOnTop() {
      return this.$store.getters.alwaysOnTop
    },

    breakAlwaysOnTop() {
      return this.$store.getters.breakAlwaysOnTop
    },

    autoStartWorkTimer() {
      return this.$store.getters.autoStartWorkTimer
    },

    autoStartBreakTimer() {
      return this.$store.getters.autoStartBreakTimer
    },

    minToTray() {
      return this.$store.getters.minToTray
    },

    minToTrayOnClose() {
      return this.$store.getters.minToTrayOnClose
    },

    notifications() {
      return this.$store.getters.notifications
    },

    rightClickToResetRound() {
      return this.$store.getters.rightClickToResetRound
    },

    os() {
      return this.$store.getters.os
    },

    tickSounds() {
      return this.$store.getters.tickSounds
    },

    tickSoundsDuringBreak() {
      return this.$store.getters.tickSoundsDuringBreak
    },

    globalShortcuts() {
      return this.$store.getters.globalShortcuts
    }
  },

  methods: {
    selectAlwaysOnTop() {
      const payload = {
        key: 'alwaysOnTop',
        val: !this.alwaysOnTop
      }
      ipcRenderer.send('toggle-alwaysOnTop', !this.alwaysOnTop)
      this.$store.dispatch('setSetting', payload)
      this.$store.dispatch('setViewState', payload)

      if (this.alwaysOnTop === false && this.breakAlwaysOnTop === true) {
        this.$refs.breakAlwaysOnTopCheckbox.click()
      }
    },

    selectBreakAlwaysOnTop() {
      const payload = {
        key: 'breakAlwaysOnTop',
        val: !this.breakAlwaysOnTop
      }

      ipcRenderer.send('toggle-breakAlwaysOnTop', !this.breakAlwaysOnTop)
      this.$store.dispatch('setSetting', payload)
      this.$store.dispatch('setViewState', payload)
    },

    selectAutoStartWorkTimer() {
      const payload = {
        key: 'autoStartWorkTimer',
        val: !this.autoStartWorkTimer
      }
      this.$store.dispatch('setSetting', payload)
      this.$store.dispatch('setViewState', payload)
    },

    selectAutoStartBreakTimer() {
      const payload = {
        key: 'autoStartBreakTimer',
        val: !this.autoStartBreakTimer
      }
      this.$store.dispatch('setSetting', payload)
      this.$store.dispatch('setViewState', payload)
    },

    selectMinToTray() {
      const payload = {
        key: 'minToTray',
        val: !this.minToTray
      }
      ipcRenderer.send('toggle-minToTray', !this.minToTray)
      this.$store.dispatch('setSetting', payload)
      this.$store.dispatch('setViewState', payload)
    },

    selectMinToTrayOnClose() {
      const payload = {
        key: 'minToTrayOnClose',
        val: !this.minToTrayOnClose
      }
      this.$store.dispatch('setSetting', payload)
      this.$store.dispatch('setViewState', payload)
    },

    selectNotifications() {
      const payload = {
        key: 'notifications',
        val: !this.notifications
      }
      this.$store.dispatch('setSetting', payload)
      this.$store.dispatch('setViewState', payload)
    },

    selectTickSounds() {
      this.$store.dispatch('setTickSounds', !this.tickSounds)
    },

    selectTickSoundsDuringBreak() {
      this.$store.dispatch(
        'setTickSoundsDuringBreak',
        !this.tickSoundsDuringBreak
      )
    },

    selectRightClickToResetRound() {
      const payload = {
        key: 'rightClickToResetRound',
        val: !this.rightClickToResetRound
      }
      this.$store.dispatch('setSetting', payload)
      this.$store.dispatch('setViewState', payload)
    },

    setGlobalShortcut(event, shortcut) {
      const newShortcut = JSON.parse(JSON.stringify(this.globalShortcuts))
      newShortcut[event] = shortcut
      this.$store.dispatch('setGlobalShortcuts', newShortcut)
      ipcRenderer.send('reload-global-shortcuts', newShortcut)
    }
  },
  components: {
    ShortcutInput
  }
}
</script>

<style lang="scss" scoped>
.Checkbox {
  background-color: var(--color-background);
  border: 2px solid var(--color-background-lightest);
  border-radius: 100%;
  display: inline-block;
  transition: $transitionDefault;
  width: 16px;
  height: 16px;
  &:hover {
    border-color: var(--color-accent);
  }
  &.is-active {
    background-color: var(--color-accent);
    border-color: var(--color-background);
    &:hover {
      background-color: var(--color-accent);
      border-color: var(--color-background-lightest);
    }
  }
}

.Container {
  max-height: calc(100% - 36px);
  overflow-y: auto;
}

.Setting-wrapper {
  background-color: var(--color-background);
  border-radius: 4px;
  display: flex;
  justify-content: space-between;
  margin: 12px 0;
  padding: 12px;
}

.Setting-title {
  color: var(--color-foreground-darker);
  font-size: 14px;
  letter-spacing: 0.05em;
}
</style>
