// src/lib/components/drawer/DrawerTimer.svelte
<script lang="ts">
  // Timer configuration: work/break durations and long-break interval.
  import { settings } from '$lib/stores/settings';
  import { setSetting, resetSettings } from '$lib/ipc';

  const MAX_MINS = 90;
  const MAX_ROUNDS = 12;

  // Local slider values in minutes (derived from the store).
  let workMins = $derived(Math.round($settings.time_work_secs / 60));
  let shortMins = $derived(Math.round($settings.time_short_break_secs / 60));
  let longMins = $derived(Math.round($settings.time_long_break_secs / 60));
  let rounds = $derived($settings.long_break_interval);

  function pct(val: number, max: number) {
    return (val / max) * 100;
  }

  async function handleChange(dbKey: string, rawValue: number) {
    const updated = await setSetting(dbKey, String(rawValue));
    settings.set(updated);
  }

  async function handleReset() {
    const updated = await resetSettings();
    settings.set(updated);
  }
</script>

<div class="panel">
  <p class="heading">Timer</p>

  <!-- Focus -->
  <div class="row">
    <p class="label">Focus</p>
    <p class="value">{workMins}:00</p>
    <div class="slider-wrap">
      <input
        type="range" min="1" max={MAX_MINS} step="1"
        value={workMins}
        class="slider"
        oninput={(e) => handleChange('time_work_mins', (e.target as HTMLInputElement).valueAsNumber)}
      />
      <div class="bar bar--focus" style="width: {pct(workMins, MAX_MINS)}%"></div>
    </div>
  </div>

  <!-- Short Break -->
  <div class="row">
    <p class="label">Short Break</p>
    <p class="value">{shortMins}:00</p>
    <div class="slider-wrap">
      <input
        type="range" min="1" max={MAX_MINS} step="1"
        value={shortMins}
        class="slider"
        oninput={(e) => handleChange('time_short_break_mins', (e.target as HTMLInputElement).valueAsNumber)}
      />
      <div class="bar bar--short" style="width: {pct(shortMins, MAX_MINS)}%"></div>
    </div>
  </div>

  <!-- Long Break -->
  <div class="row">
    <p class="label">Long Break</p>
    <p class="value">{longMins}:00</p>
    <div class="slider-wrap">
      <input
        type="range" min="1" max={MAX_MINS} step="1"
        value={longMins}
        class="slider"
        oninput={(e) => handleChange('time_long_break_mins', (e.target as HTMLInputElement).valueAsNumber)}
      />
      <div class="bar bar--long" style="width: {pct(longMins, MAX_MINS)}%"></div>
    </div>
  </div>

  <!-- Rounds -->
  <div class="row">
    <p class="label">Rounds</p>
    <p class="value">{rounds}</p>
    <div class="slider-wrap">
      <input
        type="range" min="1" max={MAX_ROUNDS} step="1"
        value={rounds}
        class="slider"
        oninput={(e) => handleChange('work_rounds', (e.target as HTMLInputElement).valueAsNumber)}
      />
      <div class="bar bar--rounds" style="width: {pct(rounds, MAX_ROUNDS)}%"></div>
    </div>
  </div>

  <!-- Reset -->
  <div class="row row--center">
    <button class="text-btn" onclick={handleReset}>Reset Defaults</button>
  </div>
</div>

<style>
  .panel {
    padding: 8px 12px;
    overflow-y: auto;
    height: 100%;
  }

  .heading {
    font-size: 0.7rem;
    font-weight: 700;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    color: var(--color-foreground-darker, var(--color-foreground));
    margin-bottom: 8px;
    padding-bottom: 6px;
    border-bottom: 1px solid var(--color-separator);
  }

  .row {
    margin: 10px 0;
    text-align: center;
  }

  .row--center {
    margin-top: 16px;
  }

  .label {
    color: var(--color-foreground-darker, var(--color-foreground));
    font-size: 0.8rem;
    letter-spacing: 0.05em;
    margin-bottom: 4px;
  }

  .value {
    background: var(--color-background);
    border-radius: 4px;
    display: inline-block;
    font-family: monospace;
    font-size: 0.75rem;
    padding: 2px 8px;
    margin-bottom: 6px;
  }

  .slider-wrap {
    position: relative;
    height: 20px;
    display: flex;
    align-items: center;
  }

  .slider {
    position: relative;
    z-index: 2;
    width: 100%;
    -webkit-appearance: none;
    appearance: none;
    height: 4px;
    background: transparent;
    outline: none;
    cursor: pointer;
  }

  .slider::-webkit-slider-thumb {
    -webkit-appearance: none;
    appearance: none;
    width: 14px;
    height: 14px;
    border-radius: 50%;
    background: var(--color-foreground);
    cursor: pointer;
  }

  .slider::-moz-range-thumb {
    width: 14px;
    height: 14px;
    border-radius: 50%;
    background: var(--color-foreground);
    cursor: pointer;
    border: none;
  }

  .bar {
    position: absolute;
    left: 0;
    height: 4px;
    border-radius: 2px;
    pointer-events: none;
    z-index: 1;
    transition: width 0.05s;
  }

  .bar--focus  { background: var(--color-focus-round); }
  .bar--short  { background: var(--color-short-round); }
  .bar--long   { background: var(--color-long-round); }
  .bar--rounds { background: var(--color-foreground-darker, var(--color-foreground)); }

  .text-btn {
    background: none;
    border: none;
    cursor: pointer;
    color: var(--color-foreground-darker, var(--color-foreground));
    font-size: 0.8rem;
    padding: 4px 8px;
    border-radius: 4px;
    transition: color 0.15s;
  }

  .text-btn:hover {
    color: var(--color-accent);
  }
</style>

// src/renderer/components/drawer/Drawer-timer.vue
<template>
  <div class="Container">
    <p class="Drawer-heading">Timer</p>
    <div class="Setting-wrapper">
      <p class="Setting-title">Work</p>
      <p class="Setting-value">{{ localTimeWork + ':00' }}</p>
      <div class="Slider-wrapper">
        <input 
          type="range" 
          min="1" 
          :max="maxTime" 
          step="1" 
          class="Slider Slider--red" 
          v-model.number="localTimeWork" 
          @change="setTimeWork($event, 'work')"
        >
        <div 
          class="Slider-bar Slider-bar--red" 
          :style="{ width: calcPercentage(localTimeWork, maxTime) + '%' }">
        </div>
      </div>
    </div>

    <div class="Setting-wrapper">
      <p class="Setting-title">Short Break</p>
      <p class="Setting-value">{{ localTimeShortBreak + ':00' }}</p>
      <div class="Slider-wrapper">
        <input 
          type="range" 
          min="1" 
          :max="maxTime" 
          step="1" 
          class="Slider Slider--green" 
          v-model.number="localTimeShortBreak"
          @change="setTimeShortBreak($event, 'short-break')"
        >
        <div 
          class="Slider-bar Slider-bar--green" 
          :style="{ width: calcPercentage(localTimeShortBreak, maxTime) + '%' }">
        </div>
      </div>
    </div>

    <div class="Setting-wrapper">
      <p class="Setting-title">Long Break</p>
      <p class="Setting-value">{{ localTimeLongBreak + ':00' }}</p>
      <div class="Slider-wrapper">
        <input 
          type="range" 
          min="1" 
          :max="maxTime" 
          step="1" 
          class="Slider Slider--blue" 
          v-model.number="localTimeLongBreak"
          @change="setTimeLongBreak($event, 'long-break')"
        >
        <div 
          class="Slider-bar Slider-bar--blue" 
          :style="{ width: calcPercentage(localTimeLongBreak, maxTime) + '%' }">
        </div>
      </div>
    </div>

    <div class="Setting-wrapper">
      <p class="Setting-title">Rounds</p>
      <p class="Setting-value">{{ localWorkRounds }}</p>
      <div class="Slider-wrapper">
        <input 
          type="range" 
          min="1" 
          :max="maxRounds" 
          step="1" 
          class="Slider" 
          v-model.number="localWorkRounds"
          @change="setWorkRounds"
        >
        <div 
          class="Slider-bar Slider-bar--blueGrey" 
          :style="{ width: calcRoundPercentage(localWorkRounds, maxRounds) + '%' }">
        </div>
      </div>
    </div>

    <div class="Setting-wrapper">
      <p class="TextButton" @click="resetDefaults">Reset Defaults</p>
    </div>
  </div>
</template>

<script>
import { EventBus } from '@/utils/event-bus'

export default {
  name: 'Drawer-timer',

  data () {
    return {
      localTimeLongBreak: 0,
      localTimeShortBreak: 0,
      localTimeWork: 0,
      localWorkRounds: 0,
      maxTime: 60,
      maxRounds: 12
    }
  },

  computed: {
    // store getters
    currentRound () {
      return this.$store.getters.currentRound
    },

    timeLongBreak () {
      return this.$store.getters.timeLongBreak
    },

    timeShortBreak () {
      return this.$store.getters.timeShortBreak
    },

    timeWork () {
      return this.$store.getters.timeWork
    },

    workRounds () {
      return this.$store.getters.workRounds
    }
  },

  methods: {
    calcPercentage (val, max) {
      return val / max * 100
    },

    // complex conditional to correctly position slider-bar for round slider
    calcRoundPercentage (val, max) {
      const percentage = val / max * 100
      if (percentage > 25 && percentage < 34) {
        return percentage - 6
      } else if (percentage > 33 && percentage < 66) {
        return percentage - 5.5
      } else if (percentage > 50) {
        return percentage - 4
      } else {
        return percentage - 7
      }
    },

    checkToResetTimer (setting) {
      if (this.currentRound === setting) {
        EventBus.$emit('timer-init', {
          auto: false
        })
        EventBus.$emit('call-timer-reset')
      }
    },

    initTimes () {
      this.localTimeLongBreak = this.timeLongBreak
      this.localTimeShortBreak = this.timeShortBreak
      this.localTimeWork = this.timeWork
      this.localWorkRounds = this.workRounds
    },

    resetDefaults () {
      this.$store.dispatch('resetDefaults')
      this.initTimes()
      EventBus.$emit('timer-init', {
        auto: false
      })
      EventBus.$emit('call-timer-reset')
    },

    setTimeLongBreak (e, setting) {
      this.$store.dispatch('setTimeLongBreak', e.target.value)
      this.checkToResetTimer(setting)
    },

    setTimeShortBreak (e, setting) {
      this.$store.dispatch('setTimeShortBreak', e.target.value)
      this.checkToResetTimer(setting)
    },

    setTimeWork (e, setting) {
      this.$store.dispatch('setTimeWork', e.target.value)
      this.checkToResetTimer(setting)
    },

    setWorkRounds (e, setting) {
      this.$store.dispatch('setWorkRounds', e.target.value)
    }
  },

  mounted () {
    this.initTimes()
  }
}
</script>

<style lang="scss" scoped>
.Setting-wrapper {
  margin: 10px 0;
  text-align: center;
}

.Setting-title {
  color: $colorBlueGrey;
  font-size: 14px;
  letter-spacing: .05em;
  margin-bottom: 8px;
}

.Setting-value {
  background-color: $colorNavy;
  border-radius: 4px;
  display: inline-block;
  font-family: 'RobotoMono', monospace;
  font-size: 12px;
  padding: 2px 6px;
}

.Slider-wrapper {
  position: relative;
}

.Slider {
  position: relative;
  width: 100%;
  -webkit-appearance: none;
  &:focus {
    outline: 0;
  }
  &::-webkit-slider-runnable-track {
    background-color: $colorNavy;
    width: 100%;
    height: 3px;
  }
  &::-webkit-slider-thumb {
    background-color: $colorBlueGrey;
    border: 2px solid $colorBlueGrey;
    border-radius: 100%;
    margin-top: -7px;
    width: 15px;
    height: 15px;
    -webkit-appearance: none;
    -webkit-app-region: no-drag;
  }
}

.Slider--blue {
  &::-webkit-slider-thumb {
    background-color: $colorBlue;
    border: 2px solid $colorBlue;
    -webkit-app-region: no-drag;
  }
}

.Slider--green {
  &::-webkit-slider-thumb {
    background-color: $colorGreen;
    border: 2px solid $colorGreen;
    -webkit-app-region: no-drag;
  }
}

.Slider--red {
  &::-webkit-slider-thumb {
    background-color: $colorRed;
    border: 2px solid $colorRed;
    -webkit-app-region: no-drag;
  }
}

.Slider-bar {
  position: absolute;
  top: calc(50% + 3px);
  height: 3px;
}

.Slider-bar--blue {
  background-color: $colorBlue;
}

.Slider-bar--blueGrey {
  background-color: $colorBlueGrey;
}

.Slider-bar--green {
  background-color: $colorGreen;
}

.Slider-bar--red {
  background-color: $colorRed;
}
</style>
